### ISSUE TITLE
import aria  error

### ISSUE THREAD

**Issue by jth445600** [SahilKr24/kuebikobot#21]
[root@centos-s-1vcpu-1gb-sfo3-01 kuebikobot]# python --version
Python 2.7.5
[root@centos-s-1vcpu-1gb-sfo3-01 kuebikobot]# vim aria.py 
[root@centos-s-1vcpu-1gb-sfo3-01 kuebikobot]#  python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 7, in <module>
    import aria
  File "/root/workspace/kuebikobot/aria.py", line 8, in <module>
    host = socket.gethostbyname('aria2-pro')
socket.gaierror: [Errno -2] Name or service not known

**Comment by sentinm** [comment]
> [root@centos-s-1vcpu-1gb-sfo3-01 kuebikobot]# python --version
> Python 2.7.5
> [root@centos-s-1vcpu-1gb-sfo3-01 kuebikobot]# vim aria.py
> [root@centos-s-1vcpu-1gb-sfo3-01 kuebikobot]# python3 bot.py
> Traceback (most recent call last):
> File "bot.py", line 7, in
> import aria
> File "/root/workspace/kuebikobot/aria.py", line 8, in
> host = socket.gethostbyname('aria2-pro')
> socket.gaierror: [Errno -2] Name or service not known

````sh
2021-07-26T17:59:49.011218+00:00 heroku[worker.1]: State changed from starting to up
2021-07-26T17:59:53.592728+00:00 heroku[worker.1]: Process exited with status 1
2021-07-26T17:59:53.670010+00:00 heroku[worker.1]: State changed from up to crashed
2021-07-26T17:59:53.453471+00:00 app[worker.1]: Traceback (most recent call last):
2021-07-26T17:59:53.453507+00:00 app[worker.1]:   File "/usr/src/app/bot.py", line 7, in <module>
2021-07-26T17:59:53.453883+00:00 app[worker.1]:     import aria
2021-07-26T17:59:53.454503+00:00 app[worker.1]:   File "/usr/src/app/aria.py", line 8, in <module>
2021-07-26T17:59:53.455308+00:00 app[worker.1]:     host = socket.gethostbyname('aria2-pro')
2021-07-26T17:59:53.455349+00:00 app[worker.1]: socket.gaierror: [Errno -2] Name or service not known
```

I'm also having this error while deploying in heroku stack: container :flushed:
